### PR TITLE
[#104897322] Use BOSH deployed postgres instead of RDS on AWS

### PR DESCRIPTION
**Pull request by keymon**
Related: [#104897322 Use postgres instead of using RDS for BOSH database in AWS](https://www.pivotaltracker.com/story/show/104897322)
# What

On AWS we currently use RDS for the UAA and Cloudcountroller in CF instead of a VM deployed by BOSH, which is slower to deploy and is more expensive (doesn't shut down with the rest of the environment).

We want to change this to use the same structure as in AWS and GCE
## Scope

We want to: 
- Stop using RDS but a VM running postgres for CCDB and UAADB,
  in the same way as we do in GCE.
- make both environments more similar, using the common
  denominator
- Remove the RDS references
# How to review this?

If you already have a running environment on AWS, the fastest option without destroying everything:
1. Delete the deployment with `bosh delete deployment cloudfoundry-<env>`
2. Deploy it again: `bosh deploy`
3. Apply terraform to delete the RDS references: `make apply-aws DEPLOY_ENV=...`
4. Run the tests `make test-aws DEPLOY_ENV=...` (note, you need #39 )
5. Run again a end-to-end deployment to be sure: `make aws DEPLOY_ENV=....`

If you don't have an environment:
1. Deploy everything: `make aws DEPLOY_ENV=...`
2. Run smoke tests:  `make test-aws DEPLOY_ENV=...` (note, you need #39 )
## who can review this?

Anyone but @saliceti or @keymon

### CODE REVIEW

**Comment by dcarley** [comment]
Attempted to test on AWS and GCE, both of which failed for seemingly unrelated reasons. I'll try again tomorrow morning.

**Comment by dcarley** [comment]
I managed to get this deployed on AWS and GCE, but both gave me the same smoke test failure. The tests ran OK after switching back to `master` and deploying again. Any idea why?

```
• Failure in Spec Setup (BeforeEach) [0.644 seconds]
Loggregator: [BeforeEach]
/home/ubuntu/cf-smoke-tests/smoke/logging/loggregator_test.go:42
  cf logs
  /home/ubuntu/cf-smoke-tests/smoke/logging/loggregator_test.go:41
    can see app messages in the logs
    /home/ubuntu/cf-smoke-tests/smoke/logging/loggregator_test.go:40

    Expected
        <int>: 1
    to match exit code:
        <int>: 0

    /home/ubuntu/cf-smoke-tests/Godeps/_workspace/src/github.com/cloudfoundry-incubator/cf-test-helpers/cf/as_user.go:41
```

**Comment by keymon** [comment]
I got that error a pair of times with the smoke test. They seem related to logs, and I think it has nothing to do with the PR.

Can you please check if `cf logs any_deployed_app --recent` works? If it does, just rerun the test.

**Comment by mtekel** [comment]
every time you redeploy from a different branch, you also restart some
jobs. In this case it seems like some transient/race condition bug with
loggregator/other CF jobs. What usually fixes this is ssh to the job & do
monit restart all. We have yet to investigate why this is happening. I have
also seen this several times on master in past month...

**Comment by dcarley** [comment]
`cf logs postgresql-cf-service-broker --recent` works on both providers, but the tests still fail. This is after a new deployment from this branch (which would have restarted the jobs again).

**Comment by dcarley** [comment]
Hector noted that it was using the wrong password:

```
API endpoint: https://api.dcarley.cf.paas.alphagov.co.uk
Authenticating...
FAILED
Credentials were rejected, please try again.

[2015-10-08 15:22:13.31 (UTC)]> cf delete-space CF-SMOKE-SPACE -f
Not logged in. Use 'cf login' to log in.
```

Rebased against master for 838835cfa2088090298cc35a03886b76ab6c7147 and now working

**Pull request merged**
