### PR TITLE
[#104310224] Pin the dependencies used in the build: bosh_cli

### PR DESCRIPTION
**Pull request by keymon**
[#104310224 Pin the dependencies used in the build: bosh_cli](https://www.pivotaltracker.com/story/show/104310224)
# What

The latest publish version of `net-ssh`, which `bosh_cli` depends on, requires ruby 2.0. But Ruby 2.0 is not installed by default in the bastion host and it fails. To workaround this issue and any future one, we want to pin all the `bosh_cli` and its dependencies.
# Context

In order to pin `bosh_cli` and its dependencies, we will use a `Gemfile` and `Gemfile.lock` with bundler. This PR does:
- Install bundler from apt repository
- Defines a Gemfile pinning `bosh_cli` and `net-ssh` to the right version (latest version of `net-ssh` that works on ruby 1.9 is 2.9.1)
# How to test this.

You only need to run the install dependencies of provision.sh. For that:
1. Optional: Add a `exit 0` after `install_dependencies` in `scripts/provision.sh` to stop after install dependencies.
2. Run `make aws DEPLOY_ENV=<env>` or `make gce DEPLOY_ENV=<env>`
3. Once it is finish, check that `bosh` command line is installed in the bastion.
# Who can review this

Anyone buy @keymon

### CODE REVIEW

**Comment by dcarley** [comment]
Good commit message describing the reason for explicitly pinning `net-ssh` :+1: 

We should wrap calls to `bosh` with `bundle exec bosh`. It will work without, because the gems and binstubs are installed globally, but we won't get Bundler's guarantees about sandboxing the dependencies at the correct versions e.g. if we were to downgrade one of the dependencies in the `Gemfile` on an existing machine then bosh would continue to use the latest version installed.

**Comment by keymon** [comment]
Sure, I will add bundle exec.

**Comment by keymon** [comment]
@dcarley that is done.

**Comment by dcarley** [comment]
This didn't work for me when provisioning a new bastion host. I got the following error:

```
Installing system packages...
dpkg-query: no packages found matching build-essential
dpkg-query: no packages found matching git
dpkg-query: no packages found matching zlibc
dpkg-query: no packages found matching zlib1g-dev
dpkg-query: no packages found matching ruby
dpkg-query: no packages found matching ruby-dev
dpkg-query: no packages found matching libxslt1-dev
dpkg-query: no packages found matching libxml2-dev
dpkg-query: no packages found matching libssl-dev
dpkg-query: no packages found matching libreadline6-dev
dpkg-query: no packages found matching libyaml-dev
dpkg-query: no packages found matching libsqlite3-dev
dpkg-query: no packages found matching sqlite3
dpkg-query: no packages found matching dstat
dpkg-query: no packages found matching unzip
dpkg-query: no packages found matching bundler
Installing gem packages...
./scripts/provision.sh: line 91: bundle: command not found
```

It went away when I reverted commit 9f12426b7b00cfdbedbbfd6d8b22eb0753b46f63. How important do you think that is? Do you want to revert or fix it?

**Comment by keymon** [comment]
So far the PR looks OK.

@dcarley Shall we also use NAT for the BOSH node or not? 

If we do use NAT and remove the public IP in BOSH, we are force to connect to bosh via bastion host, by SSH to bastion or using TCP tunnels or proxies.

**Comment by keymon** [comment]
I will fix it.

**Comment by keymon** [comment]
Fixed with some bash magic.

**Comment by dcarley** [comment]
Worked :+1: The bash magic makes me twitch a bit, but it doesn't matter at the moment for the evaluation.

**Pull request merged**
