### PR TITLE
[#104875328] Do not setup static IP routing for BOSH on GCE

### PR DESCRIPTION
**Pull request by keymon**
Related: [#104875328 Add a FW rule to restrict access to BOSH from Bastion host and remove the related scripts](https://www.pivotaltracker.com/story/show/104875328)
## What

We want to remove the static routing IP in GCE which is confusing and error prone.

Instead, the VMs will connect via the bastion host, which is whitelisted as a allowed IP to reach BOSH vm ports in the firewall.
## Scope

As all the CF VMs now are routed using NAT as in #34, and the right firewall rules are set as in #36 to restrict access to the BOSH vm, we do not need anymore the static routing to the BOSH public static IP.

In this PR we only remove all the code that setups this routing.
### Check deployment without the rule

Quick way in the case you got a deployment **with the rule** already there:
1. Delete the rule, by running `make delete-route-gce DEPLOY_ENV=...`
2. Check that everything related to bosh still works: `bosh vms`, `bosh recreate api_z1`... Note that for 2m the vms might appear "unresponsive"
3. Run all the script again to be sure that the rule is not created again. You should [remove this check to force the deployment of BOSH](https://github.com/alphagov/cf-terraform/blob/feature/104875328_restrict_bosh_on_gce_without_routing_hack/scripts/provision.sh#L137--1)

Slow way, in the case you don't have an environment deployed: 
1. Create the environment **from scratch** using this branch.
2. Check that the smoke tests work,
3. Verify that the routing rule is not there,
### Check firewall rule

From a different host and out of the office (e.g. bastion on AWS environment), try to connect to the ports: 22, 25250 in tcp of the BOSH ip. Also check if 53 udp (DNS) is open:
1. Check the bosh ip: `terraform output -state gce/hector021015.tfstate bosh_ip`
2. Run some tests from a remote machine (example: a VM on AWS)

```
nc -w2 -v $BOSH_IP 22
nc -w2 -v $BOSH_IP 25250
host www.google.com $BOSH_IP
```
# who can review this

Anyone  but @keymon

### CODE REVIEW

**Comment by keymon** [comment]
I  also add  a commit for https://github.com/alphagov/cf-terraform/pull/34#discussion_r41167809

**Comment by Jonty** [comment]
The test procedure is broken as the Makefile delete-route-gce task (and the script that implements it) was removed: https://github.com/alphagov/cf-terraform/commit/6414870faffc5b42093576ae9eb345e50d0df2b2#diff-b67911656ef5d18c4ae36cb6741b7965

@keymon Would you like to fix this before I continue, or shall I just bodge it?

**Comment by keymon** [comment]
I rephrased the test procedure. I wanted to mean something different.

**Comment by keymon** [comment]
@Jonty I rebased master to solve the conflict, you can merge if you want.

**Comment by Jonty** [comment]
All works as expected (I rebased against master locally so I could run the tests before you did it :D)

Merging.

**Pull request merged**
